version: '3'

services:
  com.bateeq.service.merchandiser.webapi:
    image: com.bateeq.service.merchandiser.webapi
    build:
      context: ./Com.Bateeq.Service.Merchandiser.WebApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=mssql;Database=com.moonlay.db.project;User=sa;password=Standar123;MultipleActiveResultSets=true
    ports:
      - "5001:80"
    depends_on:     
      - mssql

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Standar123
      - MSSQL_PID=Developer
    ports:
      - "1401:1433"